### ISSUE TITLE
About Training Monocular Depth Estimation

### ISSUE THREAD

**Issue by longyangqi** [LeiaInc/holopix50k#11]
Great Work！ Looking forward to the training code.
I have some questions about training on the full data(50K)

1. What's the resolution used in your training phase? Since there are different resolutions in the full dataset. And how did you preprocess the data to get the resolution, resize or crop?

2. Did you meet the situation that the disparity is negative, due to the small rotation in the dataset? 

Thanks!

**Comment by OwenHua666** [comment]
We used the 360p and resize the images in the pre processing.

We have the negative disparity during training and we use backward mapping to move pixels accordingly.

**Comment by longyangqi** [comment]
> We used the 360p and resize the images in the pre processing.
> 
> We have the negative disparity during training and we use backward mapping to move pixels accordingly.

Thanks for your reply!  
And I have another two small questions:
I have noted that sigmoid is used in the code of Monodepth2 (depth decoder), which makes the output disparity always be positive. Do you change the sigmoid activation function to another one or just output without any activation function? 
And how do you deal with the negative output when testing on other datasets, e.g. KITTI / Middlebury?

**Comment by OwenHua666** [comment]
We are still using sigmoid and we simply shift the output to the range we need.

**Comment by longyangqi** [comment]
Thanks for your quick reply!
I get it! And I'll have a try.
