### ISSUE TITLE
Guideline to Training Monocular Depth Estimation

### ISSUE THREAD

**Issue by luisdecker** [LeiaInc/holopix50k#12]
First of all, thank you very much for all the effort regarding this work! The dataset is unique on it's category! 

I am trying to train a MonodepthV2 model using your dataset, with the objective to obtain the disparity maps of the dataset with the intent to use as a GT for another Monocular Depth Estimation model, but I'm kind of stuck with what to modify on Monodepth so to adequate it to your dataset. Could you give some guidance on how to train Monodepth2 with your dataset? Or there is a better way to obtain this disparity maps? 

Thank you again for your attention and effort!

**Comment by ndahlquist** [comment]
Hi @luisdecker , there are multiple different ways to estimate disparity maps from stereo images. A simple way of doing this is with OpenCV:

```python
def estimate_disparity(imagel, imager):
    disp_res = 16  # must be k*16 for sgbm
    winsize = 5
    min_disp = -disp_res * 1
    num_disp = 2 * np.abs(min_disp)
    p1 = 8 * 3 * winsize ** 2
    p2 = 32 * 3 * winsize ** 2
    disp12_diff_max = 1
    left_matcher = cv2.StereoSGBM_create(
        minDisparity=min_disp,
        numDisparities=num_disp,
        blockSize=winsize,
        P1=p1,
        P2=p2,
        disp12MaxDiff=disp12_diff_max,
        uniquenessRatio=15,
        speckleWindowSize=0,
        speckleRange=2,
        preFilterCap=63,
        mode=cv2.STEREO_SGBM_MODE_SGBM_3WAY)
    right_matcher = cv2.ximgproc.createRightMatcher(left_matcher)

    displ = left_matcher.compute(imagel, imager)
    dispr = right_matcher.compute(imager, imagel)
    
    return displ, dispr
```

You can also look at deep neural networks for disparity estimation, which should produce better results.

**Comment by hillaric** [comment]
This is disparity negative and positive in one picture, is it reasonable?

**Comment by andrii-tsarov-leia** [comment]
@hillaric yes, images could come "converged to infinity" and in that case disparity will have one sign.
Or they could be converged to some object on the picture, in which case disparity sign in front of the object and behind the object will differ. Usually, images collected for research purposes all converged to infinity while user generated content is "randomly converged" to achieve desired effect (pop some objects off the screen for example). Holopix50k is randomly converged
