### ISSUE TITLE
Download failed

### ISSUE THREAD

**Issue by Tord-Zhang** [LeiaInc/holopix50k#20]
On Ubuntu, using  command 
`gsutil -m cp -n -r gs://holopix50k-dataset/Holopix50k/test holopix50k_data/`
get error:
BucketNotFoundException: 404 gs://holopix50k-dataset bucket does not exist.
CommandException: 1 file/object could not be transferred.

**Comment by andrii-tsarov-leia** [comment]
Issue was identified. Should be back online soon.

**Comment by Tord-Zhang** [comment]
> Issue was identified. Should be back online soon.

Thanks a lot. Any progress?

**Comment by andrii-tsarov-leia** [comment]
Everything should be back online. But I will confirm it today
